version: '3'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    depends_on:
      - zookeeper

  backend:
    build: ./back
    ports:
      - "5001:5000"  # Change this line
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
    depends_on:
      - kafka

  frontend:
    build: ./front
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    driver: bridge
